"""Initial migration

Revision ID: 1ba0bed4801b
Revises: 0cd437e0ee7d
Create Date: 2020-03-17 17:45:50.627256

"""

# revision identifiers, used by Alembic.
revision = '1ba0bed4801b'
down_revision = '0cd437e0ee7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sticker', sa.Column('sinaURL', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sticker', 'sinaURL')
    # ### end Alembic commands ###
