"""sticker init

Revision ID: 5ae48b37ae9e
Revises: 51f5ccfba190
Create Date: 2020-03-18 23:15:43.316785

"""

# revision identifiers, used by Alembic.
revision = '5ae48b37ae9e'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.Column('smmsURL', sa.String(length=100), nullable=True),
    sa.Column('sinaURL', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.Column('collect', sa.Integer(), nullable=True),
    sa.Column('fileSize', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_sticker_sid'), 'sticker', ['sid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sticker_sid'), table_name='sticker')
    op.drop_table('sticker')
    # ### end Alembic commands ###
